name:                barefun
version:             0.1.0.0
description:         Compiler for barefun project
license:             BSD3
author:              Nick Chapman
maintainer:          nic@amadido.co.uk
github:              Nick-Chapman/barefun.git

dependencies:
- ansi-terminal
- array
- async
- base >= 4.7 && < 5
- bytestring
- clock
- containers
- extra
- haskeline
- mtl
- split
- text
- time
- transformers
- unix
- word8

default-extensions:
- BangPatterns
- DataKinds
- DeriveFunctor
- DuplicateRecordFields
- EmptyCase
- FlexibleContexts
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- NondecreasingIndentation
- NumericUnderscores
- QualifiedDo
- RankNTypes
- RecursiveDo
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- TypeFamilies
- UndecidableInstances

ghc-options:
- -Werror
- -Wall
- -Wno-name-shadowing
- -O0 # asserts and faster compiles (7s to 4s)

library:
  source-dirs: src

executables:
  main.exe:
    main:                app/main.hs
    dependencies:        barefun
