(*Stage3 (ANF)*)
let k () = ()
let _ = PRIM_PutChar('3') in
let _ = PRIM_PutChar('>') in
let _ = PRIM_PutChar(' ') in
let con = Unit0 in
let c = PRIM_GetChar(con) in
let _ = PRIM_PutChar(c) in
let con = Unit0 in
let c = PRIM_GetChar(con) in
let _ = PRIM_PutChar(c) in
let con = Unit0 in
let c = PRIM_GetChar(con) in
let _ = PRIM_PutChar(c) in
let _ = PRIM_PutChar('\n') in
let _ = PRIM_PutChar(c) in
let _ = PRIM_PutChar(c) in
let _ = PRIM_PutChar(c) in
let _ = PRIM_PutChar('\n') in
let _ = PRIM_PutChar(c) in
let _ = PRIM_PutChar(c) in
let _ = PRIM_PutChar(c) in
let _ = PRIM_PutChar('\n') in
let _ = PRIM_PutChar(c) in
let _ = PRIM_PutChar(c) in
let _ = PRIM_PutChar(c) in
let _ = PRIM_PutChar('\n') in
let _ = PRIM_PutChar(c) in
let _ = PRIM_PutChar(c) in
let _ = PRIM_PutChar(c) in
let prim = PRIM_PutChar('\n') in
k prim
