(*Stage4 (CCF)*)
let k () = ()
let g1 = Unit0 in
let g2 = Unit0 in
let g3 = Unit0 in
let t1 = PRIM_PutChar('3') in
let t2 = PRIM_PutChar('>') in
let t3 = PRIM_PutChar(' ') in
let t4 = PRIM_GetChar(g1) in
let t5 = PRIM_PutChar(t4) in
let t6 = PRIM_GetChar(g2) in
let t7 = PRIM_PutChar(t6) in
let t8 = PRIM_GetChar(g3) in
let t9 = PRIM_PutChar(t8) in
let t10 = PRIM_PutChar('\n') in
let t11 = PRIM_PutChar(t4) in
let t12 = PRIM_PutChar(t6) in
let t13 = PRIM_PutChar(t8) in
let t14 = PRIM_PutChar('\n') in
let t15 = PRIM_PutChar(t6) in
let t16 = PRIM_PutChar(t8) in
let t17 = PRIM_PutChar(t4) in
let t18 = PRIM_PutChar('\n') in
let t19 = PRIM_PutChar(t8) in
let t20 = PRIM_PutChar(t4) in
let t21 = PRIM_PutChar(t6) in
let t22 = PRIM_PutChar('\n') in
let t23 = PRIM_PutChar(t4) in
let t24 = PRIM_PutChar(t6) in
let t25 = PRIM_PutChar(t8) in
let t26 = PRIM_PutChar('\n') in
k t26
